#!/usr/bin/env node

var uc = require('ugrid').context();
var da1 = uc.parallelize([1, 2, 3]);
var da2 = uc.parallelize(['a', 'b', 'c']);
da1.cartesian(da2).collect().on('data', console.log).on('end', uc.end);
