#!/usr/bin/env node

var trace = require('line-trace');
var Chance = require('chance');
var chance = new Chance();

var text, targetLength = process.argv[2] || 1000, length = 0;

trace(targetLength);
while (length < targetLength) {
	text = chance.paragraph();
	length += text.length + 1;
	console.log(text);
}
