#!/usr/local/bin/node --harmony

// Example of a subscriber

var co = require('co');
var grid = require('../lib/ugrid-client.js')({host: 'localhost', port: 12346, data: {type: 'sub'}});

co(function *() {
	yield grid.connect();
	var pub = yield grid.devices({type: 'pub'});
	console.log(pub[0]);
	if (pub[0]) {
		grid.subscribe([pub[0]]);
		console.log('subscribed');
	} else process.exit(1);
	//setInterval(function () {
	//	grid.unsubscribe([pub[0]]);
	//	console.log('unsubscribe !');
	//}, 10000);
	grid.on('publish', function(msg) {
		console.log(msg);
	});
})();
