#!/usr/local/bin/node --harmony

var fs = require('fs');
var readline = require('readline');
var co = require('co');

var grid = require('../lib/ugrid-client.js')({data: {type: 'wc1'}});

var input = process.argv[2] || '/etc/hosts';

co(function *() {
	yield grid.connect();
	var wc2 = yield grid.devices({type: 'wc2'});
	var msg = {id: wc2[0].id, cmd: 'line'};
	var rl = readline.createInterface({
		input: fs.createReadStream(input, {encoding: 'utf8'}),
		output: process.stdout, terminal: false
	});
	rl.on('line', function (line) {
		var w, words = line.split(/\W+/), res = {};
		for (var i in words) {
			w = words[i];
			if (!w) continue;
			res[w] = res[w] ? res[w] + 1: 1;
		}
		//console.log(Object.keys(res).length);
		msg.data = res;
		grid.send_cb(0, msg);
	});
	rl.on('close', function () {
		msg.cmd = 'end';
		msg.data = '';
		grid.send_cb(0, msg);
		process.exit(0);
	});
})();
