#!/usr/local/bin/node --harmony

// word count collector. Start wc2 first, then wc1

var co = require('co');
var grid = require('../lib/ugrid-client.js')({data: {type: 'wc2'}});

co(function *() {
	yield grid.connect();
	var words = {};
	grid.on('line', function (msg) {
		for (var i in msg.data) {
			if (!words[i])
				words[i] = msg.data[i];
			else
				words[i] += msg.data[i];
		}
	});
	grid.on('end', function (msg) {
		console.log(words);
		process.exit(0);
	});
})();
