#!/usr/local/bin/node --harmony

var co = require('co');
var grid = require('../../lib/ugrid-client.js')({data: {type: 'pub'}});

var count = 0;

co(function *() {
	yield grid.connect();
	setInterval(function() {
		console.log('publishing ' + count);
		grid.publish(count++);
	}, 1000);
})();
