#!/usr/local/bin/node

var fs = require('fs');
var rl = require('../lib/lines.js')();
var input = process.argv[2] ? fs.createReadStream(process.argv[2]) : process.stdin;

input.pipe(rl)

rl.on('data', function (line) {
	console.log('line: ' + line);
});
